// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {responses} from '../models';

export function Calcular(arg1:string):Promise<responses.CalculoResponse>;

export function Greet(arg1:string):Promise<string>;
